export const SET_NEWEST_LAUNCH = "SET_NEWEST_LAUNCH";
export const SET_FUTURE_LAUNCH = "SET_FUTURE_LAUNCH";
export const SET_PAST_LAUNCH = "SET_PAST_LAUNCH";
export const SET_LATEST_LAUNCH = "SET_LATEST_LAUNCH";
